/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import Eser from "./eser.glb";

export default function Model(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF(Eser);
    return (
        <group ref={group} {...props} dispose={null}>
            <group position={[0, 1.55, 4.69]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere001.geometry}
                    position={[0.11, -0.27, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere002.geometry}
                    position={[0.08, -0.24, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere003.geometry}
                    position={[0, -0.19, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere004.geometry}
                    position={[0.02, -0.12, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere005.geometry}
                    position={[0.07, -0.06, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere006.geometry}
                    position={[0.13, 0.01, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere007.geometry}
                    position={[0.08, 0.09, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere008.geometry}
                    position={[0.12, 0.1, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere009.geometry}
                    position={[0.01, 0.04, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere010.geometry}
                    position={[0.11, 0.22, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere011.geometry}
                    position={[0.12, 0.26, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere012.geometry}
                    position={[0.05, -0.25, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere013.geometry}
                    position={[0.09, -0.31, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere014.geometry}
                    position={[0.07, -0.32, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere015.geometry}
                    position={[0.03, -0.28, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere016.geometry}
                    position={[0.03, -0.31, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere017.geometry}
                    position={[-0.01, -0.3, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere018.geometry}
                    position={[-0.07, -0.29, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere019.geometry}
                    position={[-0.07, -0.23, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere020.geometry}
                    position={[-0.1, -0.26, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere021.geometry}
                    position={[-0.08, -0.28, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere022.geometry}
                    position={[-0.01, -0.23, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere023.geometry}
                    position={[-0.01, -0.18, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere024.geometry}
                    position={[0, -0.11, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere025.geometry}
                    position={[0.05, -0.04, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere026.geometry}
                    position={[0.09, 0.02, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere027.geometry}
                    position={[-0.02, 0.04, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere028.geometry}
                    position={[-0.04, 0.06, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere029.geometry}
                    position={[0.1, 0.24, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere030.geometry}
                    position={[0.12, 0.27, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere031.geometry}
                    position={[0.1, 0.28, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere032.geometry}
                    position={[0.08, 0.28, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere033.geometry}
                    position={[0.03, 0.28, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere034.geometry}
                    position={[0.02, 0.3, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere035.geometry}
                    position={[0.02, 0.32, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere036.geometry}
                    position={[-0.03, 0.29, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere037.geometry}
                    position={[-0.01, 0.3, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere038.geometry}
                    position={[-0.07, 0.3, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere039.geometry}
                    position={[-0.08, 0.27, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere040.geometry}
                    position={[-0.06, 0.25, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere041.geometry}
                    position={[-0.12, 0.25, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere042.geometry}
                    position={[-0.12, 0.22, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere043.geometry}
                    position={[0, 0.12, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere044.geometry}
                    position={[-0.04, 0.1, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere045.geometry}
                    position={[-0.03, 0.09, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere046.geometry}
                    position={[-0.05, 0.1, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere047.geometry}
                    position={[-0.07, 0.07, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere048.geometry}
                    position={[-0.11, 0.11, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere049.geometry}
                    position={[-0.13, 0.12, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere050.geometry}
                    position={[-0.06, 0.15, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere051.geometry}
                    position={[-0.11, 0.18, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere052.geometry}
                    position={[-0.13, 0.14, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere053.geometry}
                    position={[0.06, 0.18, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere054.geometry}
                    position={[0.03, 0.23, 0]}
                />
                <mesh
                    material={materials["1_1k_k�releri"]}
                    geometry={nodes.Sphere055.geometry}
                    position={[-0.04, 0.22, 0]}
                />
            </group>
            <group position={[-0.01, 1.29, 4.68]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh
                    material={materials["eser_ahsap_i�_"]}
                    geometry={nodes.Box003.geometry}
                    position={[0.21, 0.27, 0.13]}
                    rotation={[Math.PI / 2, 0, Math.PI]}
                />
                <mesh
                    material={materials["eser_ahsap_i�_"]}
                    geometry={nodes.Box001.geometry}
                    position={[0.29, 0.24, 0]}
                    rotation={[-Math.PI, 0, 2.71]}
                />
                <mesh
                    material={materials["eser_ahsap_i�_"]}
                    geometry={nodes.Box002.geometry}
                    position={[-0.25, 0.18, 0.13]}
                    rotation={[Math.PI / 2, 0, Math.PI]}
                />
            </group>
            <group position={[0.21, 1.28, 4.54]} rotation={[-Math.PI, 0, -Math.PI]}>
                <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                    <mesh material={materials["06 - Default23"]} geometry={nodes.mesh_79.geometry} />
                    <mesh material={materials.cark2} geometry={nodes.mesh_79_1.geometry} />
                    <mesh material={materials.carkic} geometry={nodes.mesh_79_2.geometry} />
                </group>
                <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                    <mesh material={materials["06 - Default23"]} geometry={nodes.mesh_80.geometry} />
                    <mesh material={materials.carkic} geometry={nodes.mesh_80_1.geometry} />
                </group>
                <mesh
                    material={materials["06 - Default23"]}
                    geometry={nodes.Circle008.geometry}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    material={materials["06 - Default23"]}
                    geometry={nodes.Circle009.geometry}
                    position={[0, 0, -0.01]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
            </group>
            <group position={[0.23, 1.42, 4.54]} rotation={[-Math.PI, 0, -Math.PI]}>
                <group position={[0, 0, 0.01]} rotation={[Math.PI / 2, 0, Math.PI]}>
                    <mesh material={materials["06 - Default23"]} geometry={nodes.mesh_83.geometry} />
                    <mesh material={materials["cark-buyuk"]} geometry={nodes.mesh_83_1.geometry} />
                </group>
                <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, Math.PI]}>
                    <mesh material={materials["06 - Default23"]} geometry={nodes.mesh_84.geometry} />
                    <mesh material={materials.carkic} geometry={nodes.mesh_84_1.geometry} />
                </group>
                <mesh
                    material={materials["06 - Default23"]}
                    geometry={nodes.Circle005.geometry}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, Math.PI]}
                />
                <mesh
                    material={materials["06 - Default23"]}
                    geometry={nodes.Circle006.geometry}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, Math.PI]}
                />
            </group>
            <mesh
                material={materials.mavi}
                geometry={nodes.Shape003.geometry}
                position={[-0.01, 1.73, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <group position={[0.13, 1.22, 4.54]} rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh material={materials["06 - Default23"]} geometry={nodes.mesh_56.geometry} />
                <mesh material={materials.carkic} geometry={nodes.mesh_56_1.geometry} />
            </group>
            <mesh
                material={materials["eser_ahsap_i�_"]}
                geometry={nodes.Box004.geometry}
                position={[-0.14, 1.5, 4.55]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <group position={[0.13, 1.22, 4.54]} rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh material={materials["06 - Default23"]} geometry={nodes.mesh_58.geometry} />
                <mesh material={materials["cark-buyuk"]} geometry={nodes.mesh_58_1.geometry} />
                <mesh material={materials.carkic} geometry={nodes.mesh_58_2.geometry} />
            </group>
            <mesh
                material={materials["06 - Default23"]}
                geometry={nodes.Circle013.geometry}
                position={[0.13, 1.22, 4.55]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
                material={materials["06 - Default23"]}
                geometry={nodes.Circle014.geometry}
                position={[0.13, 1.22, 4.55]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
                material={materials["01 - Default"]}
                geometry={nodes.Rectangle001.geometry}
                position={[0, 1.22, 4.69]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
                material={materials.mavi}
                geometry={nodes.Line011.geometry}
                position={[-0.1, 1.65, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <mesh
                material={materials.beyaz}
                geometry={nodes.Line013.geometry}
                position={[-0.03, 1.47, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <mesh
                material={materials.mavi}
                geometry={nodes.Line031.geometry}
                position={[-0.1, 1.65, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <mesh
                material={materials.k1rm1z1}
                geometry={nodes.Line029.geometry}
                position={[-0.03, 1.47, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <mesh
                material={materials.cam}
                geometry={nodes.Line030.geometry}
                position={[0.01, 1.39, 4.68]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <mesh
                material={materials.k1rm1z1}
                geometry={nodes.Line028.geometry}
                position={[0.08, 1.8, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <mesh
                material={materials["05 - Default"]}
                geometry={nodes.Line002.geometry}
                position={[-0.04, 1.26, 4.55]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                material={materials["05 - Default34"]}
                geometry={nodes.Line001.geometry}
                position={[-0.04, 1.26, 4.8]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                material={materials.mavi}
                geometry={nodes.Line007.geometry}
                position={[0.01, 1.39, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <mesh
                material={materials.totem}
                geometry={nodes.Shape001.geometry}
                position={[-0.01, 1.73, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <mesh
                material={materials.beyaz}
                geometry={nodes.Shape002.geometry}
                position={[-0.01, 1.73, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.45, 1.07, 1.45]}
            />
            <mesh
                material={materials.mavi}
                geometry={nodes.Shape004.geometry}
                position={[-0.01, 1.73, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <mesh
                material={materials.k1rm1z1}
                geometry={nodes.Shape005.geometry}
                position={[-0.01, 1.73, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.45, 1.07, 1.45]}
            />
            <mesh
                material={materials.mavi}
                geometry={nodes.Circle021.geometry}
                position={[-0.01, 1.73, 4.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.07, 1.07, 1.07]}
            />
            <mesh
                material={materials.totem}
                geometry={nodes.Box005.geometry}
                position={[-0.01, 0, 4.68]}
                rotation={[-Math.PI, 0, -Math.PI]}
            />
        </group>
    );
}

useGLTF.preload("/eser.gltf");
